services:
  app:
    build: .
    image: true-news
    volumes:
      - "./src:/app/src"
      - "./main.py:/app/main.py"
      - "./tmp:/app/tmp"
      - "./data:/app/data"
    command: [ "uv", "run", "python", "main.py" ]
