"""empty message

Revision ID: 0931408ae0e5
Revises: 4a39dcd5d5f3
Create Date: 2026-03-30 18:14:49.342878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0931408ae0e5'
down_revision: Union[str, Sequence[str], None] = '4a39dcd5d5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsers', schema=None) as batch_op:
        batch_op.alter_column('kwargs_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsers', schema=None) as batch_op:
        batch_op.alter_column('kwargs_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
