"""empty message

Revision ID: d2332a3191e9
Revises: 3939702b1e6c
Create Date: 2026-04-01 15:14:20.597323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2332a3191e9'
down_revision: Union[str, Sequence[str], None] = '3939702b1e6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanning_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scanning-history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scanning-history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scanning_history')
    # ### end Alembic commands ###
